AWSTemplateFormatVersion: '2010-09-09'
Description: 'EchoGuard Frontend Deployment with AWS Amplify'

Parameters:
  ApiEndpoint:
    Type: String
    Description: API Gateway endpoint URL
    Default: https://j5pdd9cbul.execute-api.us-east-1.amazonaws.com/prod

Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: EchoGuard
      Description: EchoGuard Voice-to-Text Compliance Logger
      Repository: https://github.com/yourusername/echoguard
      AccessToken: '{{resolve:secretsmanager:AmplifyGitHubToken:SecretString:token}}'
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - npm ci
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: build
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      EnvironmentVariables:
        - Name: REACT_APP_API_ENDPOINT
          Value: !Ref ApiEndpoint
      IAMServiceRole: !GetAtt AmplifyServiceRole.Arn

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: main
      EnableAutoBuild: true
      EnvironmentVariables:
        - Name: REACT_APP_API_ENDPOINT
          Value: !Ref ApiEndpoint

  AmplifyServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

Outputs:
  AmplifyAppId:
    Description: Amplify App ID
    Value: !GetAtt AmplifyApp.AppId
  
  DefaultDomain:
    Description: Default domain for the Amplify app
    Value: !Sub ${AmplifyApp.DefaultDomain}
  
  MainBranchURL:
    Description: URL for the main branch
    Value: !Sub https://${AmplifyBranch.BranchName}.${AmplifyApp.DefaultDomain}